# Generated by Django 2.1.15 on 2020-12-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gxibie', models.CharField(max_length=20, verbose_name='所属系别')),
                ('gname', models.CharField(max_length=20, verbose_name='班级班号')),
                ('gdate', models.DateField(verbose_name='创建日期')),
                ('ggirlnum', models.IntegerField(verbose_name='女生人数')),
                ('gboynum', models.IntegerField(verbose_name='男生人数')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snum', models.CharField(max_length=20, verbose_name='学生学号')),
                ('sname', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('ssex', models.CharField(max_length=20, verbose_name='学生性别')),
                ('sage', models.IntegerField(verbose_name='学生年龄')),
                ('stab', models.CharField(max_length=20, verbose_name='联系方式')),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Grades', verbose_name='所属班级')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
